
name: Build Spotube Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Spotube
        uses: actions/checkout@v4
        with:
          repository: KRTirtho/spotube
          ref: v3.7.1 # Puedes cambiar esto a la versión que desees

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17" # Bajamos a 17 para que Gradle no explote

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.0 # Esta es compatible con la mayoría de paquetes actuales
          cache: true

      - name: Get dependencies
        run: |
          flutter pub get
          # Si vuelve a fallar el 'get', intenta: flutter pub upgrade --major-versions

      - name: Build APK
        run: flutter build apk --release --split-per-abi --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: spotube-apk
          path: build/app/outputs/flutter-apk/*.apk
